### ISSUE TITLE
classes with a single pausable method incorrectly identified as SAMs

### ISSUE THREAD

**Issue by nqzero** [kilim/kilim#38]
classes with a single pausable method are incorrectly identified as functional interfaces

see examples/Userdata.java in https://github.com/nqzero/kilim/tree/srl.icce

specifically https://github.com/nqzero/kilim/commit/a352bc26ae2be84e11d24c7fcf64d7131c55957c

/*
this class fails with:
java.lang.IncompatibleClassChangeError: Found class kilim.examples.Userdata$Eats1, but interface was expected
    at kilim.examples.Userdata.$shim$1(Userdata.java)
    at kilim.examples.Userdata.execute(Userdata.java:27)
    at kilim.Task._runExecute(Task.java:435)
    at kilim.WorkerThread.run(WorkerThread.java:32)
*/

**Comment by nqzero** [comment]
this is fixed in [kilim 2.0](https://github.com/nqzero/kilim) in https://github.com/nqzero/kilim/commit/79ca1908e79fe6d6a7a15e0abe89fbe46c4b76e8
