### ISSUE TITLE
Using error reporting in spring projects

### ISSUE THREAD

**Issue by wylsource** [kilim/kilim#61]
![image](https://user-images.githubusercontent.com/26646077/62750027-3c86c400-ba91-11e9-81bb-c35d8ae4beb6.png)
It's the boot method.

The following is the exception information started:
Connected to the target VM, address: '127.0.0.1:59025', transport: 'socket'
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at kilim.tools.Kilim.trampoline(Kilim.java:113)
	at kilim.tools.Kilim.trampoline(Kilim.java:65)
	at com.star.demo.BootDemoApplication.main(BootDemoApplication.java:11)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kilim.WeavingClassLoader.run(WeavingClassLoader.java:122)
	at kilim.tools.Kilim.trampoline(Kilim.java:110)
	... 2 more
Caused by: java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:438)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:420)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:413)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:269)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:250)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1214)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1203)
	at com.star.demo.BootDemoApplication.main(BootDemoApplication.java:14)
	... 8 more
Caused by: java.lang.IllegalArgumentException: class org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer is not assignable to interface org.springframework.context.ApplicationContextInitializer
	at org.springframework.util.Assert.assignableCheckFailed(Assert.java:673)
	at org.springframework.util.Assert.isAssignable(Assert.java:604)
	at org.springframework.util.Assert.isAssignable(Assert.java:635)
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:432)
	... 15 more

And finally, my pom.xml file.

<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.7.RELEASE</version>
        <relativePath/> 
    </parent>
    <groupId>com.star</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>boot-demo</name>
    <description>Demo project for Spring Boot</description>

    <properties>
        <java.version>1.8</java.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.db4j</groupId>
            <artifactId>kilim</artifactId>
            <version>2.0.2</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.db4j</groupId>
                <artifactId>kilim</artifactId>
                <version>2.0.2</version>
                <executions>
                    <execution>
                        <goals><goal>weave</goal></goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

能不能帮忙看下原因

**Comment by nqzero** [comment]
you're using the weaver in the pom, so i doubt you need the trampoline in this case

if you do, i think this is probably a case of kilim not seeing the correct parent classloader. you can call `trampoline(Object example,boolean check,String...args)` where example is either a class that you want to weave or an instance of that class. then kilim will use the classloader for that example as it's parent

**Comment by wylsource** [comment]
Thank you for your answer, but I have another problem.
I commented out the code in the main method and started it properly, but I couldn't use task in my code
![image](https://user-images.githubusercontent.com/26646077/62843733-c8495c00-bcee-11e9-9565-2a51e3945e08.png)

When I call this interface, I report an error.
![image](https://user-images.githubusercontent.com/26646077/62843764-06468000-bcef-11e9-825a-90950d7183c5.png)
The error message is as follows:
![image](https://user-images.githubusercontent.com/26646077/62843788-3857e200-bcef-11e9-87c3-7a693575dbad.png)

Then, if I use the maven command “mvn clean package” to package the project into a jar package and then start it with the “java -jar” name, the interface can be accessed normally. What is the reason for this? Is there any way to start kilim directly without hitting jar?

The development tool I'm using is "Intellij IDEA"

**Comment by nqzero** [comment]
the weaving occurs during the process-classes phase of the maven project. i'm not that familiar with intellij, but i believe it bypasses maven when running code. there may be a way to disable that

one note: you're using `result.putb` inside of your task. this will cause it to block. you probably want to use `result.put()` instead

**Comment by wylsource** [comment]
OK, I see. Thank you very much for your answer. I'll ask you later if I have any questions.

**Comment by nqzero** [comment]
@wylsource  i will download intellij and try it, and see if i can find an easier way to run. i'll also look at using runtime weaving with spring
