### ISSUE TITLE
java.lang.reflect.InvocationTargetException JDK 11, 8 works fine

### ISSUE THREAD

**Issue by crazzmc** [kilim/kilim#73]
**Version:** classpath group: 'org.db4j', name: 'kilim', version: '2.0.2'
No errors if I use JDK 8. Only happening with 11. Any ideas? Thanks in advance!

`java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at kilim.tools.Kilim.trampoline(Kilim.java:113)
	at kilim.tools.Kilim.trampoline(Kilim.java:79)
	at io.ruin.GameServer.main(GameServer.java:77)
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at kilim.WeavingClassLoader.run(WeavingClassLoader.java:122)
	at kilim.tools.Kilim.trampoline(Kilim.java:110)
	... 2 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

	at com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:244)
	at com.ea.agentloader.AgentLoader.loadAgent(AgentLoader.java:77)
	at com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:148)
	at com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:102)
	at io.ruin.GameServer.main(GameServer.java:80)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:240)
	... 12 more
Caused by: java.lang.RuntimeException: java.io.IOException: Can not attach to current VM
Caused by: java.lang.RuntimeException: java.io.IOException: Can not attach to current VM

	at com.ea.agentloader.AgentLoaderHotSpot.getVirtualMachine(AgentLoaderHotSpot.java:90)
	at com.ea.agentloader.AgentLoaderHotSpot.loadAgent(AgentLoaderHotSpot.java:56)
	... 17 more
Caused by: java.io.IOException: Can not attach to current VM
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.<init>(HotSpotVirtualMachine.java:75)
Caused by: java.io.IOException: Can not attach to current VM

	at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:48)
	at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:69)
	at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
	at com.ea.agentloader.AgentLoaderHotSpot.getVirtualMachine(AgentLoaderHotSpot.java:86)
	... 18 more
java.io.FileNotFoundException: null\errors.txt (The system cannot find the path specified)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:158)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:82)
	at io.ruin.api.utils.SimpleLogger.log(SimpleLogger.java:38)
	at io.ruin.api.utils.ServerWrapper.logError(ServerWrapper.java:26)
	at io.ruin.api.process.ProcessFactory.lambda$static$0(ProcessFactory.java:10)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1055)
	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1050)
	at java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:2001)
`

**Comment by Shadowrs** [comment]
I believe this was Runite related not kilim but don't remember exactly.

**Comment by nqzero** [comment]
what game is this ? how can we reproduce the problem ?

looks like they used kilim ! pretty exciting :)
